language: java
jdk: openjdk11
sudo: false
services:
  - docker
  - mongodb

env:
  global:
    - IMAGE=asrr/cosmos
    - DEPLOYMENT=cosmos
    - NAMESPACE=asrr

before_install:
  - chmod +x gradlew
  - chmod +x scripts/push_image.sh
  - chmod +x scripts/deploy.sh
  - pip install --user codecov

script:
  - ./gradlew build

after_success:
  - ./scripts/push_image.sh
  - ./scripts/deploy.sh
  - codecov

cache:
  directories:
    - $HOME/.gradle
    - $HOME/kubernetes