server:
  servlet:
    context-path: /api/v1
  error:
    include-stacktrace: always

spring:
  application:
    name: Cosmos
  data:
    mongodb:
      host: database.asrr-tech.com
      port: 27017
      database: cosmos
      authentication-database: admin
      username: admin
      password: bTciStoOeXpenSivE
  profiles:
    active: local


springdoc:
  swagger-ui:
    path: /docs
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    path: /api-docs

