server:
  servlet:
    context-path: /api/v1

spring:
  application:
    name: Cosmos
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cosmos
  profiles:
    active: local

springdoc:
  swagger-ui:
    path: /docs
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    path: /api-docs


